FROM terrestris/openjdk-maven-docker:jdk17-bullseye

WORKDIR /shogun/example-backend

ENTRYPOINT [ \
  "mvn", \
  "spring-boot:run", \
  "-Dspring-boot.run.profiles=base,boot,example-backend", \
  "-Dspring-boot.run.jvmArguments=-Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:4711 -Djdk.serialSetFilterAfterRead=true", \
  "-Djava.security.egd=file:/dev/./urandom", \
  "-Dcom.sun.management.jmxremote", \
  "-Dcom.sun.management.jmxremote.port=9010", \
  "-Dcom.sun.management.jmxremote.rmi.port=9010", \
  "-Dcom.sun.management.jmxremote.local.only=false", \
  "-Dcom.sun.management.jmxremote.authenticate=false", \
  "-Dcom.sun.management.jmxremote.ssl=false" \
]
